### ISSUE TITLE
Cross-dimensional teleportation broken again

### ISSUE THREAD

**Issue by CDAGaming** [samueljtaylor/SimpleCommands#8]
This feature is broken in v1.0, multiple regressions seen from v0.4.0 when I fixed this before.

**Comment by samueljtaylor** [comment]
I completely rewrote the mod as it was old code from the original fork, either way it's fixed in v1.0.1.

**Comment by CDAGaming** [comment]
@samueljtaylor Re-open. This did not effect just /home.
